= GHA Build Example

A place to experiment with getting GitHub Actions to build like we'd like it to.
If successful, we might even leave this repo around as an example/reference for those with similar build tastes.

== Current Snags

=== GHA must be enabled for forks
GitHub Actions must be enabled by the user for forks.

Problematic? Dunno, maybe, maybe not, but good to note.

Our premise that folks are typically using GHA on forks to verify before submitting PRs might be incorrect.
But that does not invalidate our approach.
They could be using GHA on forks.
If they want to.

=== Removing `synchronize` from `pull_request` does not work for forked PRs
I removed `synchronize` from `pull_request` and this gives desired test workflow triggering for local branches/PRs.
But for forks, tests are run on the fork only and not as checks for PR.

So it seems we'd like:
- please run tests on fork if not PRed yet.
- please run tests on PR if PRed. No need to run them on fork.
Can we express that?
I think we need to restore `synchronize` `pull_request` activity.

So what are asking for, really?
If a PR has been opened we do not need a duplicate test run.
For a forked PR, the PR checks seem to need to be from pull_request synchronize.
For a local branch PR, the PR checks are corallated (and duplicated) from pull_request synchronize and push.

Instead of removing `synchronize` can we suppress the `push` trigger when in a PR?

Maybe.

I can use `gh`, the github command line tool to search if the current commit sha is part of a PR.
So if the triggering event is `push` and the sha is in a PR, tests should be skipped.

I've tried doing this at the step level.
Ex. Job step 1 sets a var that step 2 consults to determine if it should run.

This is interesting but working at the step level is not terribly useful.
Next up: I'll try skipping at the job level.
Does GitHub Actions allow for that?

Maybe.

TODO:
1. Currently when merging a PR to master, I'm skipping tests.
The event is push and th commit is part of PR.
So I'd need to tweak that.
We also want to run tests on PR merge.


== Build Goals

We want tests to be run on pushes everywhere (forks or not) so that folks can verify their work before submitting PRs.
When it comes time to publish a release, we want that to be triggered on a version tag.

Trigger tests for:

* push to master or any other branch [verified]
* push to fork of this repo [gha must be enabled for fork]
* push to PR
** from local branch [verified]
** from fork [nope, does not work, runs tests on fork, but does not run tests as checks for PR]

Some specific desired behaviour:

1. Trigger tests to run only once when working from a PR.
We need the tests to be perceived by GitHub as checks for the PR.
2. On publish, triggered by a version tag push, trigger a test run, then follow that up with a release work.
An additional test run should not be triggered here.
3. Publish work should not be executed when on a fork.

Notes:

GitHub actions allows some control over what invokes a workflow.
But some controls are only available at the job level within a workflow.
So sometimes we'll trigger a workflow but skip all the jobs in that workflow.
Just because that's the way GitHub Actions currenltly works.

The duplicate test run on PR is uglier when the PR is from a local branch.
In this case both test runs are attached as checks to the PR.

If the PR is from a fork, we still have the duplicate test run, but the fork test run is not part of the checks.

We can determine if GHA is running from a fork via: `github.event.pull_request.head.repo.fork`.
Not sure if this will be helpful.

Scenarios:

A commit push should trigger tests. No need to explain more here.

An automated publish commit push (one that bumps version in files) should not trigger tests.
The automation will use the convention of starting commit messages with `publish:`.

A automated publish version tag push should trigger the publish workflow, which should trigger tests workflow.
The version tag should not directly trigger a tests flow.
Version tag convention is to start tag with `v`.
