= GHA Build Example

A place to experiment with getting GitHub Actions to build like we'd like it to.
If successful, we might even leave this repo around as an example/reference for those with similar build tastes.

== Current Snags

=== GHA must be enabled for forks
1. GitHub Actions must be enabled by the user for forks.
Problematic? Dunno, maybe, maybe not, but good to note.

=== Removing `synchronize` from `pull_request` does not work for forked PRs
I removed `synchronize` from `pull_request` and this gives desired test workflow triggering for local branches/PRs.
But for forks, tests are run on the fork only and not as checks for PR.

So it seems we'd like:
- please run tests on fork if not PRed yet.
- please run tests on PR if PRed. No need to run them on fork.
Can we express that?
I think we need to restore `synchronize` `pull_request` activity.

So what are asking for?

Instead of removing `synchronize` can we suppress the `push` trigger when in a PR?
Dunno, will explore more.

== Build Goals

We want tests to be run on pushes everywhere (forks or not) so that folks can verify their work before submitting PRs.
When it comes time to publish a release, we want that to be triggered on a version tag.

Trigger tests for:

* push to master or any other branch [verified]
* push to fork of this repo [gha must be enabled for fork]
* push to PR
** from local branch [verified]
** from fork [nope, does not work, runs tests on fork, but does not run tests as checks for PR]

Some specific desired behaviour:

1. Trigger tests to run only once when working from a PR.
We need the tests to be perceived by GitHub as checks for the PR.
2. On publish, triggered by a version tag push, trigger a test run, then follow that up with a release work.
An additional test run should not be triggered here.
3. Publish work should not be executed when on a fork.

Notes:

GitHub actions allows some control over what invokes a workflow.
But some controls are only available at the job level within a workflow.
So sometimes we'll trigger a workflow but skip all the jobs in that workflow.
Just because that's the way GitHub Actions currenltly works.

The duplicate test run on PR is uglier when the PR is from a local branch.
In this case both test runs are attached as checks to the PR.

If the PR is from a fork, we still have the duplicate test run, but the fork test run is not part of the checks.

We can determine if GHA is running from a fork via: `github.event.pull_request.head.repo.fork`.
Not sure if this will be helpful.

Scenarios:

A commit push should trigger tests. No need to explain more here.

An automated publish commit push (one that bumps version in files) should not trigger tests.
The automation will use the convention of starting commit messages with `publish:`.

A automated publish version tag push should trigger the publish workflow, which should trigger tests workflow.
The version tag should not directly trigger a tests flow.
Version tag convention is to start tag with `v`.
