name: publish
on:
  push:
    tags:
      - 'v\d+.*'

jobs:
  test:
    if: ${{ github.repository_owner == 'clj-easy' }}
    uses: ./.github/workflows/tests.yml

  publish:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        run: echo "Publishing 456"
