name: tests
on:
  workflow_call: # allow invocation from publish
  push:
    branches:
      - "**"
    tags:
      - "!**" # only the publish flow triggers on tags
  pull_request:
    # default activity types are: synchronize, opened, reopened
    # remove synchronize to avoid double triggering on PRs commits (push trigger is enough)
    types:
      - opened
      - synchronize # add back in to explore...
      - reopened


jobs:
  test:
    permissions:
      pull-requests: read

    # the publish flow commits version changes, we don't want that, on its own, to trigger a test run
    # but we do need tests to run if invoked by publish
    if: ${{ startsWith(github.ref, 'refs/tags/v') || !startsWith(github.event.head_commit.message, 'publish:') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: pr numbers
      env:
        GH_TOKEN: ${{ github.token }}
      run: echo "PR_NUMBERS=$(gh search prs ${{ github.sha }} --json number | cat)" >> $GITHUB_ENV

    - name: Does gh cli help at all?
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Are we on a fork?: ${{ github.event.pull_request.head.repo.fork }}"
        echo "github.event_name: ${{ github.event_name }}"
        echo "github.sha: ${{ github.sha}}"
        echo "pr number? github.event.number ${{ github.event.number }}"
        echo "search prs"
        gh search prs ${{ github.sha }} --json number
        echo "learn some gha expressions syntax maybe"
        echo "prnumbers: ${{ env.PR_NUMBERS }}"
        echo "push event?: ${{ github.event_name == 'push' }}"
        echo "prnumbers?: ${{ contains( env.PR_NUMBERS, 'number:') }}"

    - name: Run tests
      run: |
        echo "Testing 123"
