name: tests
on:
  workflow_call: # allow invocation from publish
  push:
    branches:
      - "**"
    tags:
      - "!**" # only the publish flow triggers on tags
  pull_request:
    # default activity types are: synchronize, opened, reopened
    # remove synchronize to avoid double triggering on PRs commits (push trigger is enough)
    types:
      - opened
      - synchronize # add back in to explore...
      - reopened

jobs:
  checks:
    runs-on: ubuntu-latest
    outputs:
      skip_tests: $${ steps.checks.outputs.skip_tests }
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # TODO: needed?
      with:
        fetch-depth: 0

    - name: Install Babashka
      uses: DeLaGuardo/setup-clojure@10.2
      with:
        bb: 'latest'

    - name: Create check vars
      id: checks
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # TODO: passing on cmd line my lead to escape headaches? We'll see
        #
        echo ${{ toJson(github.event.head_commit) }}
        bb script/ci_check_skip_tests.clj \
          --commit-sha '${{ github.sha }}' \
          --event-name '${{ github.event_name }}'  \
          --ref '${{ github.ref }}' \
          --repo '${{ github.repository }}' \
          --commit-headline '${{ github.event.head_commit.messageHeadline }}'

  test:
    needs: [checks]
    # the publish flow commits version changes, we don't want that, on its own, to trigger a test run
    # but we do need tests to run if invoked by publish
    if: ${{ !needs.checks.outputs.skip_tests }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run tests
      run: |
        echo "Testing 123"
