name: tests
on:
  workflow_call: # allow invocation from publish
  push:
    branches:
      - "**"
    tags:
      - "!**" # only the publish flow triggers on tags
  pull_request:
    # default activity types are: synchronize, opened, reopened
    # remove synchronize to avoid double triggering on PRs commits (push trigger is enough)
    types:
      - opened
      - synchronize # add back in to explore...
      - reopened

jobs:
  checks:
    runs-on: ubuntu-latest
    outputs:
      skip_tests: $${ steps.checks.outputs.skip_tests }
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set vars
      id: vars
      run: |


    - name: Create check vars
      id: checks
      env:
        GH_TOKEN: ${{ github.token }}
      # TODO: check: if gh fails, we want this all to fail,
      # Skip tests when any of:
      # - triggered by push and in pr
      # - commit is part of publish workflow
      # - not invoked by publish
      # Hmmm... $(echo ${shell-var-name}) is a tad awkard, but hopefully it works...
      run: |
        pr_nums=$(gh search prs ${{ github.sha }} --json number --jq '.[].number')
        is_in_pr=${{ $(echo ${pr_nums}) != '' }}
        is_push=${{ github.event_name == 'push' }}
        ## This workflow ignores tags so we know it was invoked by publish if we see a version tag
        is_invoked_by_publish=${{ (startsWith(github.ref, 'refs/tags/v') }}
        is_publish_commit=${{ startsWith(github.event.head_commit.message, 'publish:')) }}
        echo "skip_tests=${{ ($(echo ${is_push}) && $(echo ${is_in_pr})) || (echo ${is_publish_commit) || !(echo ${invoked_by_publish}) }}" >> $GITHUB_OUTPUT

  test:
    needs: [checks]
    permissions:
      pull-requests: read

    # the publish flow commits version changes, we don't want that, on its own, to trigger a test run
    # but we do need tests to run if invoked by publish
    # Not sure if we can reference job output from if, might as well just try it
    if: !steps.checks.outputs.skip_tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run tests
      run: |
        echo "Testing 123"
